### ISSUE TITLE
image.load  loads an image into a torch.Tensor  Error!!!

### ISSUE THREAD

**Issue by anthonyyuan** [junhocho/SRGAN#2]
th train-SRResNet.lua -model_name 9x9-15res-LR24
{
  iter_end : 10000000
  checkpoint_start_from : ""
  beta : 0.9
  model_name : "9x9-15res-LR24"
  arch : ""
  checkpoint_save_iter : 10000
  lr : 0.001
}
ResNet-34 ImageNet  
ImageNet loaded, # of imgs:0  
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
image.load

loads an image into a torch.Tensor

> usage:
> image.load(
>     string                              -- path to file
>     [number]                            -- force destination depth: 1 | 3
>     [string]                            -- type: byte | float | double
> )
> +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
> /Users/anthonyyuan/torch/install/bin/luajit: ...s/anthonyyuan/torch/install/share/lua/5.1/dok/inline.lua:738: <image.load> missing file name
> stack traceback:
>     [C]: in function 'error'
>     ...s/anthonyyuan/torch/install/share/lua/5.1/dok/inline.lua:738: in function 'error'
>     ...s/anthonyyuan/torch/install/share/lua/5.1/image/init.lua:345: in function 'load'
>     ./src/util.lua:13: in function 'crop_SR_LR_patches'
>     ./src/util.lua:52: in function 'setBatch'
>     train-SRResNet.lua:104: in main chunk
>     [C]: in function 'dofile'
>     ...yuan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
>     [C]: at 0x01092febc0

**Comment by junhocho** [comment]
Have you ran `th prepImageNet.lua` first?
You have 0 ImageNet images loaded
